version: '3.0'
networks:
    custom-net:
        external: true
services:
  nodejs2021q4-service:
    image: nodejs2021q4-service
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
    depends_on:
      - postgres
    networks:
      - custom-net
    restart: always
    volumes:
      - ./volume-logs:/si9num/nodejs2021q4-service/logs
      - ./:/si9num/nodejs2021q4-service/src
      
  postgres:
      image: postgres-db
      build: ./db
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      environment:
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./volume-db:/si9num/nodejs2021q4-service/db

volumes:
  volume-logs:
  volume-db:     